#!/usr/bin/env bash
# deploy-dashboards.sh — push all network-o11y-demo dashboards to Grafana Cloud.
#
# Reads credentials from:
#   grafana-cloud-api.token  — Grafana service account token (dashboard write access)
#   grafana-cloud.instance   — Grafana Cloud instance URL
#
# Dashboards are read from grafana/dashboards/*.json (generated by dashboards.py).
# They are placed in a "Network O11y Demo" folder in Grafana Cloud.
#
# Usage:
#   bash scripts/deploy-dashboards.sh
#
# To regenerate dashboard JSON before deploying:
#   python3 grafana/dashboards.py && bash scripts/deploy-dashboards.sh

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(dirname "$SCRIPT_DIR")"
DASH_DIR="$REPO_ROOT/grafana/dashboards"
TOKEN_FILE="$REPO_ROOT/grafana-cloud-api.token"
INSTANCE_FILE="$REPO_ROOT/grafana-cloud.instance"
FOLDER_UID="network-lab"
FOLDER_TITLE="Network Lab"

info()  { echo "==> $*"; }
ok()    { echo "    ✓ $*"; }
fail()  { echo "ERROR: $*" >&2; exit 1; }

# ─── Read credentials ─────────────────────────────────────────────────────────

[[ -f "$TOKEN_FILE" ]]    || fail "grafana-cloud-api.token not found at $TOKEN_FILE"
[[ -f "$INSTANCE_FILE" ]] || fail "grafana-cloud.instance not found at $INSTANCE_FILE"

TOKEN=$(cat "$TOKEN_FILE" | tr -d '[:space:]')
BASE=$(grep -i '^url:' "$INSTANCE_FILE" | awk '{print $2}' | tr -d '[:space:]')

[[ -n "$TOKEN" ]] || fail "Token file is empty"
[[ -n "$BASE"  ]] || fail "Could not read URL from grafana-cloud.instance"

info "Grafana instance: $BASE"

# ─── Verify token ────────────────────────────────────────────────────────────

info "Verifying token..."
HTTP=$(curl -s -o /dev/null -w "%{http_code}" \
  -H "Authorization: Bearer $TOKEN" \
  "$BASE/api/folders")
# 403 = token works but no folder read perms (dashboard-only token)
# 200 = full access
[[ "$HTTP" == "200" || "$HTTP" == "403" ]] \
  || fail "Unexpected HTTP $HTTP from $BASE/api/folders — check token and URL"
ok "Token valid (HTTP $HTTP)"

# ─── Ensure required plugins are installed ───────────────────────────────────
# Grafana Cloud exposes POST /api/plugins/{id}/install for admin tokens.
# This is a no-op if the plugin is already installed.

REQUIRED_PLUGINS=("volkovlabs-form-panel")

info "Checking required plugins..."
for PLUGIN_ID in "${REQUIRED_PLUGINS[@]}"; do
  STATUS_CODE=$(curl -s -o /dev/null -w "%{http_code}" \
    -H "Authorization: Bearer $TOKEN" \
    "$BASE/api/plugins/$PLUGIN_ID")

  if [[ "$STATUS_CODE" == "200" ]]; then
    ok "Plugin already installed: $PLUGIN_ID"
  else
    INSTALL_RESP=$(curl -s -w "\n%{http_code}" -X POST \
      -H "Authorization: Bearer $TOKEN" \
      -H "Content-Type: application/json" \
      "$BASE/api/plugins/$PLUGIN_ID/install")
    INSTALL_CODE=$(echo "$INSTALL_RESP" | tail -1)
    if [[ "$INSTALL_CODE" == "200" || "$INSTALL_CODE" == "201" ]]; then
      ok "Plugin installed: $PLUGIN_ID"
    else
      echo "  WARNING: Could not install $PLUGIN_ID (HTTP $INSTALL_CODE)." >&2
      echo "           Install it manually: Grafana UI → Administration → Plugins → '$PLUGIN_ID'" >&2
    fi
  fi
done

# ─── Create folder ────────────────────────────────────────────────────────────

info "Attempting to create folder '$FOLDER_TITLE' (uid: $FOLDER_UID)..."
FOLDER_RESP=$(curl -s -X POST "$BASE/api/folders" \
  -H "Authorization: Bearer $TOKEN" \
  -H "Content-Type: application/json" \
  -d "{\"uid\": \"$FOLDER_UID\", \"title\": \"$FOLDER_TITLE\"}")

FOLDER_STATUS=$(echo "$FOLDER_RESP" | python3 -c "import sys,json; d=json.load(sys.stdin); print(d.get('uid',''))" 2>/dev/null || echo "")
if [[ -n "$FOLDER_STATUS" ]]; then
  ok "Folder ready: uid=$FOLDER_STATUS"
else
  # Folder may already exist — confirm it's reachable
  EXISTING=$(curl -s -H "Authorization: Bearer $TOKEN" "$BASE/api/folders/$FOLDER_UID" \
    | python3 -c "import sys,json; d=json.load(sys.stdin); print(d.get('uid',''))" 2>/dev/null || echo "")
  if [[ -n "$EXISTING" ]]; then
    ok "Folder already exists: uid=$EXISTING"
  else
    echo "WARNING: Could not create or find folder '$FOLDER_TITLE' — deploying to root." >&2
    FOLDER_UID=""
  fi
fi

# ─── Deploy dashboards ────────────────────────────────────────────────────────

info "Deploying dashboards from $DASH_DIR ..."

DEPLOYED=0
FAILED=0

for JSON_FILE in "$DASH_DIR"/*.json; do
  NAME=$(basename "$JSON_FILE" .json)

  # Wrap the dashboard spec in the API payload
  PAYLOAD=$(python3 - "$JSON_FILE" "$FOLDER_UID" <<'PYEOF'
import sys, json

with open(sys.argv[1]) as f:
    dash = json.load(f)

dash["version"] = 0

payload = {
    "dashboard": dash,
    "overwrite": True,
    "message": "deploy-dashboards.sh",
}
folder_uid = sys.argv[2]
if folder_uid:
    payload["folderUid"] = folder_uid
print(json.dumps(payload))
PYEOF
)

  RESP=$(curl -s -X POST "$BASE/api/dashboards/db" \
    -H "Authorization: Bearer $TOKEN" \
    -H "Content-Type: application/json" \
    -d "$PAYLOAD")

  STATUS=$(echo "$RESP" | python3 -c "import sys,json; d=json.load(sys.stdin); print(d.get('status',''))" 2>/dev/null || echo "")
  URL=$(echo "$RESP"   | python3 -c "import sys,json; d=json.load(sys.stdin); print(d.get('url',''))"    2>/dev/null || echo "")

  if [[ "$STATUS" == "success" ]]; then
    ok "$NAME  →  $BASE$URL"
    DEPLOYED=$((DEPLOYED + 1))
  else
    MSG=$(echo "$RESP" | python3 -c "import sys,json; d=json.load(sys.stdin); print(d.get('message', json.dumps(d)))" 2>/dev/null || echo "$RESP")
    echo "  FAIL: $NAME — $MSG" >&2
    FAILED=$((FAILED + 1))
  fi
done

# ─── Summary ─────────────────────────────────────────────────────────────────

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo " Dashboards deployed: $DEPLOYED  |  Failed: $FAILED"
echo " Folder: $BASE/dashboards/f/$FOLDER_UID"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

[[ "$FAILED" -eq 0 ]] || exit 1
